pureftpd is configured to use puredb authentication instead of mysql

diff --git a/conf/lamp b/conf/lamp
--- a/conf/lamp
+++ b/conf/lamp
@@ -110,6 +110,9 @@ Function_Ftp()
     [dD][eE][lL])
         Del_Ftp
     ;;
+    [eE][dD][iI][tT])
+        Edit_Ftp
+	;;
     [eE][xX][iI][tT])
         exit 1
     ;;
@@ -131,13 +134,13 @@ Add_VHost()
     if [ ! -f "/usr/local/apache/conf/vhost/${domain}.conf" ]; then
         echo "======================================"
         echo " Your domain: ${domain}"
-        echo "======================================" 
+        echo "======================================"
     else
         echo "==============================="
         echo "${domain} is exist!"
         echo "==============================="
     fi
-    
+
     read -p "Do you want to add more domain name? (y/n) " add_more_domainame
 
     if [ "${add_more_domainame}" == "y" ]; then
@@ -317,7 +320,7 @@ Del_VHost()
         echo "Domain: ${domain} has been deleted."
         echo "Website files will not be deleted for security reasons."
         echo "You need to manually delete the website files."
-        echo "========================================================"    
+        echo "========================================================"
     fi
 }
 
@@ -441,14 +444,46 @@ Add_Ftp()
 {
     www_uid=`id -u www`
     www_gid=`id -g www`
-    ${MySQL_Bin} -uroot -p${mysql_root_password} -e "INSERT INTO ftpusers.users VALUES ('${ftp_account_name}', MD5('${ftp_account_password}'), ${www_uid}, ${www_gid}, '${vhostdir}', 0, 0, 0, 0, '*', '${domain}', '1', 0, 0)"
+	cat >/tmp/pass${ftp_account_name}<<EOF
+${ftp_account_password}
+${ftp_account_password}
+EOF
+	/usr/local/pureftpd/bin/pure-pw useradd ${ftp_account_name} -f /usr/local/pureftpd/etc/pureftpd.passwd -u ${www_uid} -g ${www_gid} -d ${vhostdir} -m < /tmp/pass${ftp_account_name}
     [ $? -eq 0 ] && echo "Created FTP User: ${ftp_account_name} Sucessfully." || echo "FTP User: ${ftp_account_name} already exists!"
+	rm -f /tmp/pass${ftp_account_name}
 }
 
 List_Ftp()
 {
-    ${MySQL_Bin} -uroot -p${mysql_root_password} -e "SELECT User,Dir FROM ftpusers.users users ORDER BY User ASC"
+    /usr/local/pureftpd/bin/pure-pw list -f /usr/local/pureftpd/etc/pureftpd.passwd
     [ $? -eq 0 ] && echo "List FTP User Sucessfully." || echo "Read database failed."
+}
+
+Edit_Ftp()
+{
+    List_Ftp
+    Enter_Ftp_Name
+    read -p "Enter password for ftp account ${ftp_account_name}: " ftp_account_password
+    if [ "${ftp_account_password}" != "" ]; then
+		cat >/tmp/pass${ftp_account_name}<<EOF
+${ftp_account_password}
+${ftp_account_password}
+EOF
+		/usr/local/pureftpd/bin/pure-pw passwd ${ftp_account_name} -f /usr/local/pureftpd/etc/pureftpd.passwd -m < /tmp/pass${ftp_account_name}
+		[ $? -eq 0 ] && echo "FTP User: ${ftp_account_name} change password Sucessfully." || echo "FTP User: ${ftp_account_name} change password failed!"
+		rm -f /tmp/pass${ftp_account_name}
+	else
+        echo "FTP password will no change."
+    fi
+    read -p "Enter directory for ftp account ${ftp_account_name}: " vhostdir
+	if [ "${vhostdir}" != "" ]; then
+	    www_uid=`id -u www`
+		www_gid=`id -g www`
+		/usr/local/pureftpd/bin/pure-pw usermod ${ftp_account_name} -f /usr/local/pureftpd/etc/pureftpd.passwd -u ${www_uid} -g ${www_gid} -d ${vhostdir} -m
+		[ $? -eq 0 ] && echo "FTP User: ${ftp_account_name} change diretcory Sucessfully." || echo "FTP User: ${ftp_account_name} change directory failed!"
+	else
+        echo "Directory will no change."
+    fi
 }
 
 Del_Ftp()
@@ -458,7 +493,7 @@ Del_Ftp()
     echo "Your will delete ftp user ${ftp_account_name}"
     echo "Sleep 10s,Press ctrl+c to cancel..."
     sleep 10
-    ${MySQL_Bin} -uroot -p${mysql_root_password} -e "DELETE FROM ftpusers.users WHERE User='${ftp_account_name}'"
+    /usr/local/pureftpd/bin/pure-pw userdel ${ftp_account_name} -f /usr/local/pureftpd/etc/pureftpd.passwd -m
     [ $? -eq 0 ] && echo "FTP User: ${ftp_account_name} deleted Sucessfully." || echo "FTP User: ${ftp_account_name} not exists!"
 }
 
